apiVersion: v1
kind: Pod
metadata:
  name: pod-burstable-qos
spec:
  containers:
  - name: nginx
    image: nginx:latest
    resources:                      # Memory and CPU Requests and Limits are configured                               
      limits:                       # The condition of Guaranteed QoS Class is however not fulfilled
        cpu: "500m"
        memory: "256Mi"
      requests:
        cpu: "250m"
        memory: "128Mi"
