apiVersion: v1
kind: Service
metadata:
  name: k8s-sts-service
  labels:
    app:  k8s-sts-app
spec:
  clusterIP: None  # Defines as Headless Service
  selector:
    app: custom-stateful  # Matches StatefulSet labels
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
  publishNotReadyAddresses: true  # Ensures pod DNS records even before ready